/**
 * Cloudflare Worker for sochiautoparts.ru
 *
 * This Worker serves the static site generated by the Python site generator,
 * handles API endpoints for affiliate redirects, search, and stats,
 * and provides caching/edge optimization.
 *
 * Features:
 * - Serves static HTML from GitHub Pages (creastudioai-beep.github.io/sapapp/)
 * - /api/{campaignId} — Admitad affiliate redirect
 * - /api/search?q=...&lang=ru — Client-side search (redirects to /?q=...)
 * - /api/stats — Site statistics JSON
 * - Cache API responses at edge for 1 hour
 * - Proper security headers
 * - Custom 404 page
 * - Russian locale date formatting
 *
 * Deploy:
 * 1. Create a new Worker in Cloudflare dashboard
 * 2. Copy this code into the Worker editor
 * 3. Add route: sochiautoparts.ru/* → this Worker
 * 4. Set environment variables:
 *    - GITHUB_PAGES_URL: https://creastudioai-beep.github.io/sapapp
 *    - ADMITAD_BASE_URL: https://ujhjj.com/g/on8kt46xpp3c08bd9d2c648980e865/
 *    - ADMITAD_SUBID: TEN
 * 5. Configure DNS: sochiautoparts.ru → Cloudflare proxy (orange cloud)
 */

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;

    // =========================================================================
    // API Routes
    // =========================================================================

    // Admitad affiliate redirect: /api/{campaignId}
    if (path.startsWith('/api/') && !path.includes('search') && !path.includes('stats') && !path.includes('shop')) {
      const campaignId = path.replace('/api/', '').replace(/\/$/, '');
      if (campaignId) {
        // Build Admitad redirect URL with erid and subid parameters
        const admBase = env.ADMITAD_BASE_URL || 'https://ujhjj.com/g/on8kt46xpp3c08bd9d2c648980e865/';
        const subid = env.ADMITAD_SUBID || 'TEN';
        const erid = `erid=${campaignId}`;
        const redirectUrl = `${admBase}?${erid}&subid=${subid}`;

        return Response.redirect(redirectUrl, 302);
      }
    }

    // Search API: /api/search?q=...&lang=ru
    // For static site, redirect to homepage with query parameter
    if (path === '/api/search') {
      const query = url.searchParams.get('q') || '';
      const lang = url.searchParams.get('lang') || 'ru';
      const prefix = lang === 'en' ? '/en' : '';
      return Response.redirect(`${prefix}/?q=${encodeURIComponent(query)}`, 302);
    }

    // Stats API: /api/stats
    if (path === '/api/stats') {
      const stats = {
        site: 'sochiautoparts.ru',
        generator: 'Cloudflare Worker',
        version: '28.0',
        timestamp: new Date().toISOString(),
        features: {
          archive: true,
          shop: true,
          search: true,
          admitad: true,
          amp: true,
          dark_mode: true,
          i18n: true,
        },
        telegram: {
          channel: '@sochiautoparts',
          url: 'https://t.me/sochiautoparts',
        },
      };

      return new Response(JSON.stringify(stats, null, 2), {
        headers: {
          'Content-Type': 'application/json',
          'Cache-Control': 'public, max-age=3600',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    // =========================================================================
    // Static Content Proxy from GitHub Pages
    // =========================================================================

    const githubPagesBase = env.GITHUB_PAGES_URL || 'https://creastudioai-beep.github.io/sapapp';

    // Determine the path to fetch from GitHub Pages
    let fetchPath = path;

    // Handle root path
    if (fetchPath === '/') {
      fetchPath = '/index.html';
    }

    // Handle paths without .html extension (pretty URLs)
    if (!fetchPath.includes('.')) {
      // Try with .html extension
      if (!fetchPath.endsWith('/')) {
        fetchPath = fetchPath + '.html';
      } else {
        fetchPath = fetchPath + 'index.html';
      }
    }

    // Handle /en/ prefix
    if (fetchPath.startsWith('/en') && !fetchPath.includes('.')) {
      if (fetchPath === '/en' || fetchPath === '/en/') {
        fetchPath = '/en/index.html';
      } else if (fetchPath.endsWith('/')) {
        fetchPath = fetchPath + 'index.html';
      } else {
        fetchPath = fetchPath + '.html';
      }
    }

    const upstreamUrl = `${githubPagesBase}${fetchPath}`;

    try {
      const response = await fetch(upstreamUrl, {
        method: request.method,
        headers: {
          'User-Agent': 'Cloudflare-Worker-Proxy/1.0',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
      });

      if (response.status === 404) {
        // Try index.html in directory
        const indexPath = fetchPath.replace('.html', '/index.html');
        if (indexPath !== fetchPath) {
          const indexResponse = await fetch(`${githubPagesBase}${indexPath}`);
          if (indexResponse.ok) {
            return addHeaders(indexResponse, path);
          }
        }

        // Return custom 404
        return handle404();
      }

      if (!response.ok) {
        return handle502(response.status);
      }

      return addHeaders(response, path);
    } catch (error) {
      return handle502(503);
    }
  },
};

/**
 * Add security and performance headers to the response
 */
function addHeaders(response, path) {
  const newHeaders = new Headers(response.headers);

  // Security headers
  newHeaders.set('X-Content-Type-Options', 'nosniff');
  newHeaders.set('X-Frame-Options', 'SAMEORIGIN');
  newHeaders.set('X-XSS-Protection', '1; mode=block');
  newHeaders.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  newHeaders.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');

  // Cache headers based on content type
  const contentType = response.headers.get('Content-Type') || '';

  if (contentType.includes('text/html')) {
    // HTML: cache for 10 minutes, revalidate
    newHeaders.set('Cache-Control', 'public, max-age=600, stale-while-revalidate=3600');
  } else if (contentType.includes('application/json') || contentType.includes('application/xml')) {
    // JSON/XML: cache for 1 hour
    newHeaders.set('Cache-Control', 'public, max-age=3600');
  } else if (contentType.includes('image/') || contentType.includes('font')) {
    // Static assets: cache for 7 days
    newHeaders.set('Cache-Control', 'public, max-age=604800, immutable');
  } else if (contentType.includes('text/css') || contentType.includes('javascript')) {
    // CSS/JS: cache for 1 day
    newHeaders.set('Cache-Control', 'public, max-age=86400');
  }

  // Remove GitHub Pages specific headers
  newHeaders.delete('X-GitHub-Request-Id');
  newHeaders.delete('X-Fastly-Request-Id');

  // Ensure correct content type for .html files served without extension
  if (!path.includes('.') && !newHeaders.get('Content-Type')?.includes('text/html')) {
    newHeaders.set('Content-Type', 'text/html; charset=utf-8');
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: newHeaders,
  });
}

/**
 * Custom 404 page
 */
function handle404() {
  const html = `<!DOCTYPE html>
<html lang="ru" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>404 — Страница не найдена | SOCHIAUTOPARTS</title>
<style>
:root{--primary:#2481CC;--bg-body:#0F1115;--bg-card:#161B22;--text-main:#F0F6FC;--text-muted:#8B949E;--radius-lg:16px;--font-main:'Inter',-apple-system,sans-serif;--font-display:'Manrope','Inter',sans-serif}
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
body{font-family:var(--font-main);background:var(--bg-body);color:var(--text-main);min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:2rem}
h1{font-family:var(--font-display);font-size:6rem;font-weight:800;color:var(--primary);margin-bottom:0.5rem}
p{font-size:1.25rem;color:var(--text-muted);margin-bottom:2rem}
a{display:inline-flex;align-items:center;gap:8px;padding:12px 28px;border-radius:9999px;background:var(--primary);color:#fff;text-decoration:none;font-weight:700;transition:transform 0.15s}
a:hover{transform:translateY(-2px)}
</style>
</head>
<body>
<h1>404</h1>
<p>Страница не найдена</p>
<a href="/">← На главную</a>
</body>
</html>`;

  return new Response(html, {
    status: 404,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-cache',
    },
  });
}

/**
 * 502/503 error page
 */
function handle502(status) {
  const html = `<!DOCTYPE html>
<html lang="ru" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Сервис временно недоступен | SOCHIAUTOPARTS</title>
<style>
:root{--primary:#2481CC;--bg-body:#0F1115;--text-main:#F0F6FC;--text-muted:#8B949E;--font-main:'Inter',-apple-system,sans-serif;--font-display:'Manrope','Inter',sans-serif}
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
body{font-family:var(--font-main);background:var(--bg-body);color:var(--text-main);min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:2rem}
h1{font-family:var(--font-display);font-size:3rem;font-weight:800;color:var(--primary);margin-bottom:1rem}
p{font-size:1.125rem;color:var(--text-muted);margin-bottom:2rem}
</style>
</head>
<body>
<h1>Сервис временно недоступен</h1>
<p>Попробуйте обновить страницу через несколько минут</p>
</body>
</html>`;

  return new Response(html, {
    status: status || 502,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-cache',
    },
  });
}
