"""
Client-side i18n JavaScript generator.

Generates /i18n.js that provides dynamic language switching
without page duplication. All pages are generated in Russian only;
English translation is applied client-side via JavaScript.

The script:
- Defines translation strings for all UI elements
- Reads/writes language preference to localStorage
- Translates all elements with data-i18n attributes
- Updates lang, og:locale, and hreflang attributes
- Persists language choice across page loads
"""

from .i18n import STRINGS


def generate_i18n_js() -> str:
    """Generate the complete /i18n.js file content.

    Returns:
        Complete JavaScript source code for the i18n module.
    """
    # Build the translations object as JS
    ru_strings = STRINGS.get("ru", {})
    en_strings = STRINGS.get("en", {})

    # Escape for JS single-quoted strings
    def _js_escape(s: str) -> str:
        return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "")

    ru_lines = []
    for key, val in ru_strings.items():
        ru_lines.append(f"    '{_js_escape(key)}': '{_js_escape(val)}'")

    en_lines = []
    for key, val in en_strings.items():
        en_lines.append(f"    '{_js_escape(key)}': '{_js_escape(val)}'")

    ru_obj = "{\n" + ",\n".join(ru_lines) + "\n  }"
    en_obj = "{\n" + ",\n".join(en_lines) + "\n  }"

    return f"""/**
 * SOCHIAUTOPARTS i18n — Client-Side Language Switcher
 * Auto-generated by site_generator/i18n_js.py
 *
 * Provides dynamic language switching without page duplication.
 * All pages are generated in Russian; English is applied client-side.
 */
(function() {{
  'use strict';

  var TRANSLATIONS = {{
    ru: {ru_obj},
    en: {en_obj}
  }};

  var CURRENT_LANG = 'ru';
  var STORAGE_KEY = 'sap_lang';

  function getLang() {{
    return CURRENT_LANG;
  }}

  function setLang(lang) {{
    if (!TRANSLATIONS[lang]) lang = 'ru';
    CURRENT_LANG = lang;
    try {{ localStorage.setItem(STORAGE_KEY, lang); }} catch(e) {{}}
    applyTranslations(lang);
    updateLangAttributes(lang);
    updateLangButtons(lang);
  }}

  function t(key, lang) {{
    lang = lang || CURRENT_LANG;
    var strings = TRANSLATIONS[lang] || TRANSLATIONS['ru'];
    return strings[key] || TRANSLATIONS['ru'][key] || key;
  }}

  function applyTranslations(lang) {{
    // Translate all elements with data-i18n attribute
    var elements = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < elements.length; i++) {{
      var el = elements[i];
      var key = el.getAttribute('data-i18n');
      var text = t(key, lang);
      if (text && text !== key) {{
        el.textContent = text;
      }}
    }}

    // Translate placeholders
    var placeholderEls = document.querySelectorAll('[data-i18n-placeholder]');
    for (var i = 0; i < placeholderEls.length; i++) {{
      var el = placeholderEls[i];
      var key = el.getAttribute('data-i18n-placeholder');
      var text = t(key, lang);
      if (text && text !== key) {{
        el.setAttribute('placeholder', text);
      }}
    }}

    // Translate aria-labels
    var ariaEls = document.querySelectorAll('[data-i18n-aria-label]');
    for (var i = 0; i < ariaEls.length; i++) {{
      var el = ariaEls[i];
      var key = el.getAttribute('data-i18n-aria-label');
      var text = t(key, lang);
      if (text && text !== key) {{
        el.setAttribute('aria-label', text);
      }}
    }}

    // Translate title attributes
    var titleEls = document.querySelectorAll('[data-i18n-title]');
    for (var i = 0; i < titleEls.length; i++) {{
      var el = titleEls[i];
      var key = el.getAttribute('data-i18n-title');
      var text = t(key, lang);
      if (text && text !== key) {{
        el.setAttribute('title', text);
      }}
    }}
  }}

  function updateLangAttributes(lang) {{
    // Update <html lang="...">
    var htmlEl = document.documentElement;
    if (htmlEl) {{
      htmlEl.setAttribute('lang', lang);
    }}

    // Update og:locale meta
    var ogLocale = document.querySelector('meta[property="og:locale"]');
    if (ogLocale) {{
      ogLocale.setAttribute('content', lang === 'en' ? 'en_US' : 'ru_RU');
    }}

    // Update hreflang links
    var hreflangs = document.querySelectorAll('link[rel="alternate"]');
    for (var i = 0; i < hreflangs.length; i++) {{
      // hreflang links are static, no need to change them
    }}
  }}

  function updateLangButtons(lang) {{
    var buttons = document.querySelectorAll('.lang-btn');
    for (var i = 0; i < buttons.length; i++) {{
      var btn = buttons[i];
      if (btn.getAttribute('data-lang') === lang) {{
        btn.classList.add('active');
      }} else {{
        btn.classList.remove('active');
      }}
    }}
  }}

  // Initialize on DOM ready
  function init() {{
    // Read saved language preference
    var savedLang = 'ru';
    try {{ savedLang = localStorage.getItem(STORAGE_KEY) || 'ru'; }} catch(e) {{}}
    if (!TRANSLATIONS[savedLang]) savedLang = 'ru';
    CURRENT_LANG = savedLang;

    // Apply translations
    applyTranslations(CURRENT_LANG);
    updateLangAttributes(CURRENT_LANG);
    updateLangButtons(CURRENT_LANG);
  }}

  // Expose API
  window.SAPI18n = {{
    getLang: getLang,
    setLang: setLang,
    t: t,
    applyTranslations: applyTranslations
  }};

  // Auto-init when DOM is ready
  if (document.readyState === 'loading') {{
    document.addEventListener('DOMContentLoaded', init);
  }} else {{
    init();
  }}
}})();
"""
